### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by MerlinEgalite** [MerlinEgalite/solvest#1]
- [x] Test revoke function
- [x] Add invariant testing
- [x] Add README.md
- [x] Add minter and transfer vest tests
- [x] Add NATSPECs
- [x] Should I keep in only on contract version? -> No
- [x] Check coverage
- [x] Add CI
- [x] Clean & optimize code 
- [x] Clean tests
- [x] Add event checks
- [x] Commit snapshot
